@startuml
left to right direction

:Гость: --> (Регистрация)
:Гость: --> (Просмотр расписания поездов)
:Гость: --> (Просмотр тарифов и акций)

(Регистрация)..> (Ввод ФИО):<<include>>
(Регистрация)..> (Ввод логина):<<include>>
(Регистрация)..> (Ввод пароля):<<include>>
(Регистрация)..> (Ввод телефона):<<include>>
(Регистрация)<.. (Ввод паспортных данных):<<extend>>

:Пользователь: ---|> :Гость:


:Пользователь: --> (Удалить аккаунт)
:Пользователь: --> (Редактировать аккаунт)
:Пользователь: --> (Создать пассажиров)
:Пользователь: --> (Купить билет)

(Купить билет) ..> (Ввод даты):<<include>>
(Купить билет) ..> (Ввод места отправления и прибытия):<<include>>
(Купить билет) ..> (Выбор поезда):<<include>>
(Купить билет) ..> (Выбор вагона):<<include>>
(Купить билет) ..> (Выбор места):<<include>>
(Купить билет) ..> (Добавление пассажиров):<<include>>
(Купить билет) ..> (Оплата):<<include>>

(Купить билет) <.. (Добавление РЖД бонус):<<extend>>

(Добавление пассажиров) <|-- (Выбор созданных пассажиров)
(Добавление пассажиров) <|-- (Ввод новых пассажиров)

:Администратор: ---|>:Пользователь:

:Администратор: --> (Добавление маршрута)
:Администратор: --> (Удаление маршрута)
:Администратор: -> (Редактирование маршрута)
@enduml

