@startuml

start
:Вход в систему;
:Поиска маршрута;
if (Маршрут найден) then (Да) 
:Выбор поезда;
:Выбор места;
if (Есть аккаунт) then (Да)
:Аутентификация пользователя;
else (Нет) 
:Регистрация;
endif 
:Ввод данных о пасажирах;
:Ввод дополнительных услуг;
:Оплата;
fork
:Формирование электронного билета;
fork again
:Отправка чека;
end fork
else (Нет) 
:Сообщение об отсутствие маршрута;
endif
stop

@enduml

