@startuml
left to right direction

:ML Service: --> (Токенизация симптомов)
:ML Service: --> (BERT-анализ симптомов)
:Врач: --> (Валидация медицинской\nтерминологии)
:ML Engineer: --> (Fine-tuning BERT модели)

(BERT-анализ симптомов) ..> (Токенизация симптомов): <<include>>
(Токенизация симптомов) <.. (Spell-check): <<extend>>
(BERT-анализ симптомов) <.. (Валидация медицинской\nтерминологии): <<extend>>

@enduml

