@startuml
left to right direction

:Пациент: --> (Загрузка изображений)
:Пациент: --> (Загрузка описания симптомов)
:Система хранения: --> (Сохранение в S3)

(Загрузка изображений) ..> (Валидация файлов): <<include>>
(Загрузка описания симптомов) ..> (Валидация файлов): <<include>>
(Загрузка изображений) <.. (Предпросмотр изображения): <<extend>>
(Загрузка изображений) ..> (Сохранение в S3): <<include>>
(Загрузка описания симптомов) ..> (Отправка в очередь): <<include>>

@enduml

