@startuml
left to right direction

:Пациент: --> (Регистрация в системе)
:Пациент: --> (Подтверждение email)
:Администратор: --> (Управление ролями)
:Email Service: --> (Отправка письма активации)

(Регистрация в системе) ..> (Валидация данных): <<include>>
(Регистрация в системе) ..> (Создание пользователя): <<include>>
(Регистрация в системе) ..> (Генерация токена): <<include>>
(Регистрация в системе) <.. (Подтверждение email): <<extend>>

(Подтверждение email) ..> (Отправка письма активации): <<include>>

(Управление ролями) ..> (Назначение ролей): <<include>>
(Управление ролями) ..> (Удаление ролей): <<include>>

@enduml

